language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "export BROWSER=oldfirefox"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn test
